### ISSUE TITLE
Readjust the gate to match the grid

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Hanoi#12]
@tnguyenh any chance you can modify the Gate position so they match better to the grid?

**Comment by tnguyenh** [comment]
yes

**Comment by tnguyenh** [comment]
Shapefile updated. The gates should appear completely on the lego bricks. Only one gate per brick, not all bricks have gates.

Source and sink are not affected by the rotation (however they are affected by mouse clicks). This is not a problem since there is always a gate nearby. Source and sink cannot be aligned properly on the grid for obvious reasons, so I suggest to keep them like that and remove their open/close behavior. We can adjust the design later.

I corrected the behavior when rotating (since it was not really closing or opening the rivers for water flow).
I also added a new boolean in order to use or not the table ("table_interaction") so it is still possible to test the model with only mouse click.
